// Generated by CoffeeScript 1.6.2
(function() {
  var rneedsContext;

  rneedsContext = jQuery.expr.match.needsContext;

  jQuery.fn.extend({
    /*
       Tests whether a predicate holds for some of the elements of this list.
    */

    exists: jQuery.fn.is,
    /*
       Tests whether a predicate holds for all elements of this list.
    */

    forall: function(selector) {
      return this.filter(selector).length === this.length;
    },
    /*
       Selects all elements of this list which do not satisfy a predicate.
    */

    filterNot: jQuery.fn.not,
    /*
       Applies a function f to all elements of this list.
    */

    foreach: jQuery.fn.each,
    escapedHtml: function() {
      var html;

      html = function(s) {
        return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
      };
      return html(this.html());
    }
  });

}).call(this);
