// Generated by CoffeeScript 1.6.2
(function() {
  var $main, $processed, $raw, ATTR_TRANSLATE, Editor, Parser, editor, loadDoc, parser;

  ATTR_TRANSLATE = 'data-translate';

  Parser = (function() {
    function Parser() {
      var __eachCallback, __parse;

      __eachCallback = function() {
        var $contents, $this, containBlock, textNodeOnly;

        $this = $(this);
        $contents = $this.contents();
        if ($contents.length === 0) {
          return;
        }
        textNodeOnly = $contents.forall(function() {
          return this.nodeType === 3;
        });
        if (textNodeOnly) {
          $this.attr('editable', true);
          return;
        }
        containBlock = $this.children().exists(function() {
          var _ref;

          return (_ref = $(this).css('display')) === 'block' || _ref === 'list-item';
        });
        if (containBlock) {
          $contents.filter(function() {
            return this.nodeType === 3 && $.trim(this.nodeValue) !== '';
          }).wrap('<div editable=true/>');
        } else {
          if (!containBlock) {
            $this.attr('editable', true);
          }
          return;
        }
      };
      __parse = function(data) {
        var $doc;

        $doc = $('<article/>').html(data);
        $('script', $doc).remove();
        $('*', $doc).removeAttr('class').removeAttr('id').filterNot('img').foreach(__eachCallback);
        $('[editable] [editable]', $doc).removeAttr('editable');
        $(Parser.nonsupport.join(','), $doc).removeAttr('editable');
        return $doc;
      };
      this.parse = function(data) {
        return __parse(data);
      };
    }

    Parser.prototype.parse = void 0;

    Parser.prototype.clean = function($data) {
      $('[editable]', $data).removeAttr('editable');
      $('[class]', $data).removeAttr('class');
      return $data;
    };

    Parser.nonsupport = ['pre'];

    return Parser;

  })();

  Editor = (function() {
    function Editor() {
      var self;

      this.$field = $('textarea', this.$input);
      self = this;
      this.$input.on('keypress', function(e) {
        if (e.keyCode === 13 && e.ctrlKey) {
          self.hide();
        }
        if (e.keyCode === 27) {
          return self.hide(false);
        }
      });
      this.$input.on('click', 'button', function() {
        var $this;

        $this = $(this);
        if ($this.is('.save')) {
          self.hide();
        }
        if ($this.is('.cancel')) {
          return self.hide(false);
        }
      });
    }

    Editor.prototype.$input = $('<div class="hero-unit" style="border:1px solid darkgrey; padding: 10px; position: absolute; display: none;">\n<field>\n<textarea class="input-block-level"></textarea>\n<button class="save btn btn-primary">Save (Ctrl+Enter)</button>\n<button class="cancel btn btn-danger">Cancel (Esc)</button>\n</field>\n</div>');

    Editor.prototype.$field = null;

    Editor.prototype.$currElem = null;

    Editor.prototype.save = function() {
      var val;

      if (this.$currElem == null) {
        return;
      }
      val = $.trim(this.$field.val());
      if (val === '') {
        this.$currElem.removeAttr(ATTR_TRANSLATE);
      } else {
        this.$currElem.attr(ATTR_TRANSLATE, val);
      }
      return $(editor).trigger('saved', {
        target: this.$currElem,
        data: val
      });
    };

    Editor.prototype.show = function($elem) {
      var h, left, self, top, w, _ref;

      if (this.$currElem != null) {
        return;
      }
      if ($elem == null) {
        return;
      }
      self = this;
      if ($elem.jquery == null) {
        $elem = $($elem);
      }
      $elem.addClass('editing');
      this.$currElem = $elem;
      $(this).trigger('editing');
      w = Math.max($elem.width(), 300);
      h = $elem.height();
      _ref = $elem.offset(), left = _ref.left, top = _ref.top;
      this.$field.width(w - 35).height(h + 20).val($elem.attr(ATTR_TRANSLATE));
      this.$input.appendTo('body').slideDown(function() {
        return $(self).trigger('shown');
      }).offset({
        left: left,
        top: top + h + 5
      });
      this.$field.get(0).focus();
    };

    Editor.prototype.hide = function(save) {
      var self;

      if (save == null) {
        save = true;
      }
      if (this.$currElem != null) {
        if (save) {
          this.save();
        }
        this.$currElem.removeClass('editing');
        $(this).trigger('done');
      }
      this.$field.val('');
      self = this;
      this.$input.slideUp(function() {
        self.$input.detach();
        self.$currElem = null;
        return $(self).trigger('hidden');
      });
    };

    Editor.prototype.isEditing = function() {
      return this.$currElem != null;
    };

    return Editor;

  })();

  $main = $('#main-container');

  $raw = $('#raw', $main);

  $processed = $('#processed', $main);

  parser = new Parser;

  editor = new Editor;

  loadDoc = function() {
    return $.get('translate.txt', function(data) {
      var doc;

      doc = parser.parse(data);
      return $raw.html(doc);
    }, 'html');
  };

  $(function() {
    loadDoc();
    return $(editor).on('editing', function() {
      return $raw.addClass('editing');
    }).on('done', function() {
      return $raw.removeClass('editing');
    }).on('saved', function(e, param) {
      return console.log(param);
    });
  });

  $(function() {
    $('body').on('keypress', function(e) {
      if (e.keyCode === 13 && e.ctrlKey) {
        editor.hide();
      }
      if (e.keyCode === 27) {
        return editor.hide(false);
      }
    });
    $main.on('click', 'a', function() {
      return false;
    });
    $raw.tooltip({
      selector: Parser.nonsupport.join(','),
      title: '不支持',
      container: 'body'
    });
    $raw.on('click', '[editable]', function() {
      if (editor.isEditing()) {
        return;
      }
      return editor.show(this);
    });
    return $('#result').on('show', function() {
      $('textarea', this).val(parser.clean($raw.clone()).children().html());
      return $('body').css('overflow', 'hidden');
    }).on('hidden', function() {
      return $('body').css('overflow', 'auto');
    });
  });

}).call(this);
