// Generated by CoffeeScript 1.6.2
(function() {
  var IGNORE_SELECTOR, isleaf;

  IGNORE_SELECTOR = 'strong';

  isleaf = function(elems) {
    var $elems, f;

    $elems = elems;
    if ((elems != null ? elems.jquery : void 0) == null) {
      $elems = $(elems);
    }
    f = $elems.filter(function() {
      return this.nodeType !== 3 && !$(this).is(IGNORE_SELECTOR);
    });
    return f.size() === 0;
  };

  $(function() {
    var $contents, $e, $merge, e, _i, _len;

    $contents = $('#t1').contents();
    $merge = $();
    for (_i = 0, _len = $contents.length; _i < _len; _i++) {
      e = $contents[_i];
      $e = $(e);
      console.log(e.nodeName);
      if (e.nodeName === 'BR') {
        console.log($e.css('display'));
      }
      if (e.nodeType === 3 || $e.css('display') !== 'block') {
        console.log('if');
        $merge = $merge.add($e);
      } else {
        if ($merge != null) {
          console.log('wrap');
          console.log($merge);
          $merge.wrapAll('<p/>');
          $merge = $();
        }
      }
    }
    $merge.wrapAll('<p/>');
    console.log($merge);
  });

}).call(this);
