// Generated by CoffeeScript 1.6.2
(function() {
  var $autoSave, $compare, $currEditingItem, $htmldoc, $input, $main, $original, $result, $resultText, $target, $textarea, ATTACH_ATTR_HEIGHT, DATA_ATTR_NAME, DATA_ORIGINAL_NAME, EDITING_CSS, EDITING_ITEM_CSS, EDITING_ITEM_SELECTOR, EDITING_SELECTOR, HOVER_CSS, ORIGINAL_ID_PREFFIX, TARGET_ID_PREFFIX, cancel, compare, compareDirty, compareInterval, getIframeDocument, gotoStep1, originalClick, originalMouseEnter, originalMouseLeave, save, selector, start, startEdit, stopEdit;

  DATA_ATTR_NAME = 'data-translate';

  DATA_ORIGINAL_NAME = 'data-original';

  ATTACH_ATTR_HEIGHT = 'attach_height';

  ORIGINAL_ID_PREFFIX = 'otrans_';

  TARGET_ID_PREFFIX = 'ttrans_';

  EDITING_CSS = 'editing';

  EDITING_ITEM_CSS = 'editing-item';

  HOVER_CSS = 'hover';

  EDITING_SELECTOR = '.editing';

  EDITING_ITEM_SELECTOR = '.editing-item';

  selector = 'h1,h2,h3,h4,h5,h6,p,dt,dd,li';

  $htmldoc = $('#step1 textarea');

  $main = $('#main');

  $original = $('#trans-original');

  $target = $('#trans-target');

  $input = $('#input');

  $textarea = $('#textarea');

  $autoSave = $('#autoSave');

  $compare = $('#compare');

  $result = $('#result');

  $resultText = $('textarea', $result);

  $currEditingItem = null;

  compareInterval = null;

  compareDirty = false;

  $(function() {
    return $textarea.bind('keypress', function(e) {
      if (e.keyCode === 13 && e.ctrlKey) {
        stopEdit();
      }
      if (e.keyCode === 27) {
        return stopEdit(false);
      }
    });
  });

  $(function() {
    $original.on('click', selector, originalClick);
    $('#startBtn').click(start);
    $('#gotoStep1Btn').click(gotoStep1);
    $('#saveBtn').click(save);
    $('#cancelBtn').click(cancel);
    $('#showResult').click(function() {
      var $rs;

      stopEdit();
      $rs = $original.clone();
      $('#input', $rs).remove();
      $('*', $rs).removeAttr('id');
      $resultText.val($rs.html());
      $result.slideDown();
    });
    $('#hideResult').click(function() {
      $result.slideUp();
    });
    $compare.prop('checked', true);
    $compare.change(function() {
      var needCompare;

      needCompare = $compare.prop('checked');
      if (needCompare && (compareInterval == null)) {
        $main.addClass('split');
        compareDirty = true;
        compare();
        compareInterval = setInterval(compare, 1000);
      } else if (!needCompare && compareInterval) {
        $main.removeClass('split');
        clearInterval(compareInterval);
        compareInterval = null;
      }
    });
    return $.get('translate.txt', function(respText) {
      $htmldoc.val(respText);
    }, 'html');
  });

  gotoStep1 = function() {
    $('#step1').slideDown();
    $('#step2').slideUp();
  };

  start = function() {
    var $content, id;

    $content = $('<div class="wrapper"/>').html($htmldoc.val());
    $('script', $content).remove();
    id = 1;
    $('*', $content).removeAttr('class').removeAttr('id').each(function() {
      return $(this).attr('id', ORIGINAL_ID_PREFFIX + (id++));
    });
    $('[href]', $content).attr('href', 'javascript://');
    $original.html($content.contents());
    compareDirty = true;
    $compare.change();
    $('#step1').slideUp();
    $('#step2').slideDown();
  };

  save = function() {
    stopEdit(true);
    return false;
  };

  cancel = function() {
    stopEdit(false);
    return false;
  };

  startEdit = function() {
    var $current, h, value;

    if ($currEditingItem == null) {
      return;
    }
    $current = $currEditingItem;
    $current.addClass(EDITING_ITEM_CSS);
    $original.addClass(EDITING_CSS);
    h = $current.height();
    $textarea.height(h);
    value = $current.attr(DATA_ATTR_NAME);
    $textarea.val(value != null ? value : '');
    $current.append($input);
    $input.finish();
    $input.fadeIn();
    $textarea.get(0).focus();
  };

  stopEdit = function(save) {
    var $current;

    if (save == null) {
      save = true;
    }
    if ($currEditingItem == null) {
      return;
    }
    $current = $currEditingItem;
    $input.fadeOut();
    $current.removeClass(EDITING_ITEM_CSS);
    $original.removeClass(EDITING_CSS);
    if (save) {
      $current.attr(DATA_ATTR_NAME, $textarea.val());
      compareDirty = true;
    }
    $currEditingItem = null;
  };

  originalMouseEnter = function() {
    $(this).addClass(HOVER_CSS);
  };

  originalMouseLeave = function() {
    $(this).removeClass(HOVER_CSS);
  };

  originalClick = function() {
    var $this, autoSave;

    $this = $(this);
    if ($this.is($currEditingItem)) {
      return;
    }
    autoSave = $autoSave.prop('checked');
    if ($currEditingItem != null) {
      stopEdit(autoSave);
    }
    $currEditingItem = $this;
    startEdit();
  };

  compare = function() {
    var $e, $rs, elem, h, id, value, _i, _len, _ref;

    if (!compareDirty) {
      return;
    }
    $rs = $original.clone();
    $('#input', $rs).remove();
    _ref = $('[' + DATA_ATTR_NAME + ']', $rs);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      elem = _ref[_i];
      $e = $(elem);
      value = $.trim($e.attr(DATA_ATTR_NAME));
      if (value !== '') {
        $e.text(value);
      }
      id = $e.attr('id');
      console.log(h = $('#' + id, $original).height());
      $e.height(h);
    }
    $target.html($rs.html());
    compareDirty = false;
  };

  getIframeDocument = function(iframe) {
    if (iframe.contentDocument != null) {
      return iframe.contentDocument;
    }
    if (iframe.contentWindow != null) {
      return iframe.contentWindow.document;
    }
    if (iframe.document != null) {
      return iframe.document;
    }
  };

}).call(this);
